### PR TITLE
Add cask homebrew instructions

### PR DESCRIPTION
**Pull request by nitrocode**

### CODE REVIEW

**Review by jonathancross — APPROVED** [review]

**Comment by nitrocode** [comment]
@jonathancross could this be merged?

**Comment by jonathancross** [comment]
@nitrocode  I reviewed it, but I do not have merge access.

**Comment by nitrocode** [comment]
Oh I didn't realize that. My mistake. From the commit history it looks like these people have merge access.

@objective-see @Patrick (friendly pings)

**Comment by cho-m** [comment]
@nitrocode 
Just to note, `brew cask install ...` is no longer supported by Homebrew.
```zsh
❯ brew cask install lulu
Error: Unknown command: cask
```

`brew install --cask lulu` is the current Homebrew command to install a specific Cask.
`brew install lulu` also works. See: https://github.com/Homebrew/homebrew-cask/blob/master/USAGE.md#installing-casks

**Comment by nitrocode** [comment]
Thanks for letting me know. Just updated the branch

**Pull request merged**
